name: Hello
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      HOGE: hoge
      HUGA: ${{ 123 }}
    steps:
      - run: echo "${{ github.event.*.html_url }}"
      - run: echo "${HOGE} ${HUGA}"
