name: Hello
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::This is a debug log"
