name: Hello
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      HOGE: hoge
      HUGA: ${{ 123 }}
      HTML_URL: ${{ github.event.*.html_url }}
    steps:
      - run: echo "${HTML_URL}"
      - run: echo "${HOGE} ${HUGA}"
