name: Hello
on: push
env:
  EXAMPLE: hoge
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: huga
    steps:
      - run: echo "${{ EXAMPLE }}"
      - env:
          EXAMPLE: piyo
        run: echo "${{ EXAMPLE }}"
