name: Hello
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: himitu
    steps:
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"
